Jeremy sir this is my Lab 2 part 1, please accept my pull request, give any feedback!
jschmersal-cscc/special-topics-labs-interview pull request #17
Opened 2019-10-20 20:53 UTC by pparasuram

Jeremy sir this is my Lab 2 part 1, please accept my pull request, give any feedback!

Prakash Parasuram

2019-10-21 00:56 UTC, jschmersal-cscc requested changes
I have a couple changes I'd like you to do and then you'll be good to go.

2019-10-21 00:56 UTC, jschmersal-cscc commented on pparasuram-interview-lab/Interview.md
> +## Prakash Parasuram: GitHub Lab Part Two:
It looks like you've accidentally added your interview to this PR.  Please remove this file from the PR and update it.

2019-10-21 00:56 UTC, jschmersal-cscc commented on README.md
> +* _Prakash_: I used to be a merchant marine ship engineer and rose to the rank of a 3rd engineer, so I have traveled a bit, except that most times the stay is short, Greece seems to be my favorite de
Did you stay anywhere long enough to know that you liked it?

2019-10-27 15:51 UTC, pparasuram commented
Please see if final changes are what you wanted.

2019-10-27 15:51 UTC, closed without merging

2019-10-28 00:55 UTC, jschmersal-cscc commented
Looks good!  Go ahead and submit in blackboard!